spring:
    datasource:
        # the newer driver compare to `com.mysql.jdbc.Driver`
        driver-class-name: com.mysql.cj.jdbc.Driver
        # MySQL Connector J properties to preserve instants
        url: jdbc:mysql://127.0.0.1:3306/test   # ?connectionTimeZone=LOCAL&forceConnectionTimeZoneToSession=true
        username: root
        password: somePassword

    flyway:
        url: jdbc:mysql://127.0.0.1:3306
        schemas: test
        user: root
        password: somePassword
